name: Publish

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main